{% set version = "7.0" %}
{% set test_skips = "(test_boundingbox_image.py and test_image) or (test_image.py and ImageTest)" %}

package:
  name: svg.path
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.org/packages/source/s/svg.path/svg_path-{{ version }}.tar.gz
    sha256: 9037486957cb1dcf4375ef42206499a47c111b8ffcbac6e3e55f9d079d875bb0
  - folder: src
    url: https://github.com/regebro/svg.path/archive/refs/tags/{{ version }}.tar.gz
    sha256: 4ddee994047d362a55568d03e43f0a5b9625f1f2737009a78aea74985e5919b7

build:
  number: 0
  noarch: python
  script: cd dist && {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}

test:
  source_files:
    - src/tests
    - src/README.rst
  requires:
    - pillow
    - pip
    - pytest-cov
    - python {{ python_min }}
  imports:
    - svg
    - svg.path
  commands:
    - pip check
    - cd src
    - coverage run --source=svg.path --branch -m pytest -vv --tb=long --color=yes -k "not ({{ test_skips }})"
    - coverage report --show-missing --skip-covered --fail-under=78

about:
  home: https://github.com/regebro/svg.path
  summary: SVG path objects and parser
  license: MIT
  license_file: dist/LICENSE.txt

extra:
  recipe-maintainers:
    - bollwyvl
